services:
  users:
    image: inhumanxd/softco-app

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3003:3000

    env_file:
      - .env

    container_name: softco-app
    restart: unless-stopped
